language : python
cache : false

matrix :
    include :
        - os : linux
          dist : precise
          python : 2.7
        - os : linux
          dist : trusty
          sudo : required
          python : 2.7
        - os : linux
          dist : precise
          python : 3.4
        - os : linux
          dist : trusty
          sudo : required
          python : 3.4
        - os : linux
          dist : precise
          python : 3.5
        - os : linux
          dist : trusty
          sudo : required
          python : 3.5

install :
    - pip install .
    - pip install -r requirements.txt
    - python setup.py install

script : py.test --cov=PyTeX

after_success :
    - codecov
